kumuluzee:
  name: expenses-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ExpensesDS
      connection-url: jdbc:postgresql://localhost:5432/expenses
      username: dbuser
      password: postgres
  health:
    checks:
      #data-source-health-check:
      #  type: liveness
      #  jndi-name: jdbc/ImageMetadataDS
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  metrics:
    web-instrumentation:
      - name: expenses-endpoint
        url-pattern: /v1/expenses/*